import { Recipe } from '../types';

export const AUSSIE_RECIPES: Recipe[] = [
  {
    id: 'r001',
    name: 'Aussie Lamb Chops with Roasted Veg',
    description: 'A true Aussie classic — juicy lamb chops with seasonal roasted vegetables.',
    prep_time_minutes: 15,
    cook_time_minutes: 30,
    servings: 4,
    difficulty: 'easy',
    tags: ['lamb', 'dinner', 'classic', 'gluten-free'],
    ingredients: [
      { name: 'lamb chops', amount: '8', unit: 'pieces' },
      { name: 'potatoes', amount: '4', unit: 'medium' },
      { name: 'carrots', amount: '3', unit: 'large' },
      { name: 'zucchini', amount: '2', unit: 'medium' },
      { name: 'olive oil', amount: '3', unit: 'tbsp' },
      { name: 'garlic', amount: '4', unit: 'cloves' },
      { name: 'rosemary', amount: '2', unit: 'sprigs' },
      { name: 'salt', amount: '1', unit: 'tsp' },
      { name: 'black pepper', amount: '0.5', unit: 'tsp' },
    ],
    instructions: [
      'Preheat oven to 200°C.',
      'Cut vegetables into chunks, toss with olive oil, garlic, salt and pepper.',
      'Roast vegetables for 20 minutes.',
      'Season lamb chops with salt, pepper and rosemary.',
      'Pan-fry chops 3–4 minutes each side or grill on high heat.',
      'Rest chops 5 minutes before serving with roasted veg.',
    ],
  },
  {
    id: 'r002',
    name: 'Spaghetti Bolognese',
    description: 'The Aussie family favourite — a hearty bolognese everyone loves.',
    prep_time_minutes: 10,
    cook_time_minutes: 40,
    servings: 6,
    difficulty: 'easy',
    tags: ['pasta', 'beef', 'dinner', 'family'],
    ingredients: [
      { name: 'spaghetti', amount: '500', unit: 'g' },
      { name: 'beef mince', amount: '500', unit: 'g' },
      { name: 'crushed tomatoes', amount: '400', unit: 'g' },
      { name: 'tomato paste', amount: '2', unit: 'tbsp' },
      { name: 'onion', amount: '1', unit: 'large' },
      { name: 'garlic', amount: '3', unit: 'cloves' },
      { name: 'carrot', amount: '1', unit: 'medium' },
      { name: 'celery', amount: '2', unit: 'stalks' },
      { name: 'olive oil', amount: '2', unit: 'tbsp' },
      { name: 'beef stock', amount: '125', unit: 'ml' },
      { name: 'parmesan cheese', amount: '50', unit: 'g' },
    ],
    instructions: [
      'Sauté diced onion, carrot and celery in olive oil for 5 minutes.',
      'Add garlic and cook 1 minute.',
      'Add mince and brown thoroughly.',
      'Stir in tomato paste, then crushed tomatoes and stock.',
      'Simmer uncovered 30 minutes.',
      'Cook spaghetti per packet directions. Serve topped with bolognese and parmesan.',
    ],
  },
  {
    id: 'r003',
    name: 'Chicken Schnitzel',
    description: 'Crispy crumbed chicken schnitzel — a pub classic made at home.',
    prep_time_minutes: 20,
    cook_time_minutes: 15,
    servings: 4,
    difficulty: 'medium',
    tags: ['chicken', 'dinner', 'family', 'fried'],
    ingredients: [
      { name: 'chicken breast', amount: '4', unit: 'pieces' },
      { name: 'breadcrumbs', amount: '2', unit: 'cups' },
      { name: 'flour', amount: '0.5', unit: 'cup' },
      { name: 'eggs', amount: '2', unit: 'large' },
      { name: 'milk', amount: '2', unit: 'tbsp' },
      { name: 'vegetable oil', amount: '0.5', unit: 'cup' },
      { name: 'salt', amount: '1', unit: 'tsp' },
      { name: 'lemon', amount: '1', unit: 'whole', optional: true },
    ],
    instructions: [
      'Pound chicken breasts to even 1cm thickness.',
      'Set up 3 bowls: flour, beaten egg+milk, breadcrumbs.',
      'Coat chicken in flour, dip in egg, press into breadcrumbs.',
      'Heat oil in large frypan over medium-high heat.',
      'Cook schnitzel 3–4 minutes each side until golden.',
      'Drain on paper towel, serve with lemon wedges.',
    ],
  },
  {
    id: 'r004',
    name: 'Pumpkin Soup',
    description: 'Creamy Australian pumpkin soup — perfect for winter nights.',
    prep_time_minutes: 15,
    cook_time_minutes: 35,
    servings: 6,
    difficulty: 'easy',
    tags: ['soup', 'vegetarian', 'winter', 'pumpkin'],
    ingredients: [
      { name: 'butternut pumpkin', amount: '1', unit: 'kg' },
      { name: 'onion', amount: '1', unit: 'large' },
      { name: 'garlic', amount: '2', unit: 'cloves' },
      { name: 'vegetable stock', amount: '1', unit: 'litre' },
      { name: 'cream', amount: '125', unit: 'ml' },
      { name: 'butter', amount: '30', unit: 'g' },
      { name: 'nutmeg', amount: '0.25', unit: 'tsp' },
      { name: 'crusty bread', amount: '1', unit: 'loaf', optional: true },
    ],
    instructions: [
      'Peel and dice pumpkin into 3cm pieces.',
      'Sauté onion and garlic in butter until soft.',
      'Add pumpkin and stock, bring to boil.',
      'Simmer 25 minutes until pumpkin is tender.',
      'Blend until smooth with a stick blender.',
      'Stir in cream and nutmeg. Season to taste. Serve with crusty bread.',
    ],
  },
  {
    id: 'r005',
    name: 'Vegemite Scrolls',
    description: 'The Aussie kids\' favourite lunchbox treat — cheesy Vegemite scrolls.',
    prep_time_minutes: 20,
    cook_time_minutes: 20,
    servings: 12,
    difficulty: 'easy',
    tags: ['baking', 'lunchbox', 'kids', 'snack', 'vegemite'],
    ingredients: [
      { name: 'self-raising flour', amount: '3', unit: 'cups' },
      { name: 'butter', amount: '60', unit: 'g' },
      { name: 'milk', amount: '1', unit: 'cup' },
      { name: 'vegemite', amount: '3', unit: 'tbsp' },
      { name: 'cheddar cheese', amount: '1.5', unit: 'cups' },
      { name: 'salt', amount: '0.5', unit: 'tsp' },
    ],
    instructions: [
      'Preheat oven to 200°C. Line a baking tray.',
      'Rub butter into flour and salt until breadcrumb-like.',
      'Add milk and mix to soft dough.',
      'Roll dough into 30×40cm rectangle.',
      'Spread Vegemite over dough, sprinkle cheese.',
      'Roll up tightly, cut into 12 slices.',
      'Place on tray, bake 18–20 minutes until golden.',
    ],
  },
  {
    id: 'r006',
    name: 'Barramundi with Mango Salsa',
    description: 'Fresh Aussie barramundi with a tropical mango salsa.',
    prep_time_minutes: 20,
    cook_time_minutes: 10,
    servings: 4,
    difficulty: 'medium',
    tags: ['fish', 'dinner', 'tropical', 'gluten-free', 'summer'],
    ingredients: [
      { name: 'barramundi fillets', amount: '4', unit: 'fillets' },
      { name: 'mango', amount: '1', unit: 'large' },
      { name: 'red onion', amount: '0.5', unit: 'small' },
      { name: 'lime', amount: '2', unit: 'whole' },
      { name: 'coriander', amount: '0.5', unit: 'cup' },
      { name: 'red chilli', amount: '1', unit: 'small', optional: true },
      { name: 'olive oil', amount: '2', unit: 'tbsp' },
      { name: 'salt', amount: '1', unit: 'tsp' },
    ],
    instructions: [
      'Dice mango, red onion and chilli. Mix with lime juice and coriander to make salsa.',
      'Pat barramundi fillets dry, season with salt.',
      'Heat olive oil in pan over high heat.',
      'Cook barramundi 3–4 minutes skin-side down, flip once.',
      'Cook another 2 minutes until cooked through.',
      'Serve topped with mango salsa.',
    ],
  },
  {
    id: 'r007',
    name: 'Anzac Biscuits',
    description: 'The iconic Aussie oat biscuit with a satisfying crunch.',
    prep_time_minutes: 15,
    cook_time_minutes: 15,
    servings: 24,
    difficulty: 'easy',
    tags: ['baking', 'biscuits', 'classic', 'anzac', 'snack'],
    ingredients: [
      { name: 'rolled oats', amount: '1', unit: 'cup' },
      { name: 'plain flour', amount: '1', unit: 'cup' },
      { name: 'desiccated coconut', amount: '1', unit: 'cup' },
      { name: 'sugar', amount: '1', unit: 'cup' },
      { name: 'butter', amount: '125', unit: 'g' },
      { name: 'golden syrup', amount: '2', unit: 'tbsp' },
      { name: 'bicarbonate of soda', amount: '1', unit: 'tsp' },
      { name: 'boiling water', amount: '2', unit: 'tbsp' },
    ],
    instructions: [
      'Preheat oven to 160°C. Line baking trays.',
      'Combine oats, flour, coconut and sugar in a bowl.',
      'Melt butter and golden syrup together.',
      'Mix bicarb with boiling water, add to butter mixture.',
      'Combine wet and dry ingredients.',
      'Roll tablespoons of mixture into balls, flatten on trays.',
      'Bake 12–15 minutes until golden. Cool on tray.',
    ],
  },
  {
    id: 'r008',
    name: 'Lamington Cake',
    description: 'Classic lamingtons — soft sponge squares dipped in chocolate and coconut.',
    prep_time_minutes: 30,
    cook_time_minutes: 30,
    servings: 16,
    difficulty: 'medium',
    tags: ['baking', 'dessert', 'classic', 'lamington'],
    ingredients: [
      { name: 'plain flour', amount: '2', unit: 'cups' },
      { name: 'sugar', amount: '1', unit: 'cup' },
      { name: 'butter', amount: '125', unit: 'g' },
      { name: 'eggs', amount: '4', unit: 'large' },
      { name: 'milk', amount: '0.5', unit: 'cup' },
      { name: 'icing sugar', amount: '3', unit: 'cups' },
      { name: 'cocoa powder', amount: '0.5', unit: 'cup' },
      { name: 'desiccated coconut', amount: '3', unit: 'cups' },
      { name: 'boiling water', amount: '0.5', unit: 'cup' },
    ],
    instructions: [
      'Preheat oven to 180°C. Grease a 20×30cm pan.',
      'Cream butter and sugar. Beat in eggs one at a time.',
      'Fold in flour alternately with milk.',
      'Bake 25–30 minutes. Cool overnight before cutting.',
      'Mix icing sugar, cocoa and boiling water to make icing.',
      'Cut sponge into squares, dip in icing then coconut.',
      'Set on a wire rack to dry.',
    ],
  },
  {
    id: 'r009',
    name: 'Beef and Veggie Stew',
    description: 'A hearty slow-cooked stew full of Australian root vegetables.',
    prep_time_minutes: 20,
    cook_time_minutes: 120,
    servings: 6,
    difficulty: 'easy',
    tags: ['beef', 'stew', 'winter', 'slow-cook', 'family'],
    ingredients: [
      { name: 'beef chuck', amount: '800', unit: 'g' },
      { name: 'potatoes', amount: '4', unit: 'medium' },
      { name: 'carrots', amount: '3', unit: 'large' },
      { name: 'parsnip', amount: '2', unit: 'medium' },
      { name: 'onion', amount: '2', unit: 'large' },
      { name: 'beef stock', amount: '500', unit: 'ml' },
      { name: 'tomato paste', amount: '2', unit: 'tbsp' },
      { name: 'Worcestershire sauce', amount: '2', unit: 'tbsp' },
      { name: 'flour', amount: '2', unit: 'tbsp' },
      { name: 'thyme', amount: '3', unit: 'sprigs' },
    ],
    instructions: [
      'Cut beef into 3cm cubes, dust with flour.',
      'Brown beef in batches in a large pot. Set aside.',
      'Sauté onions until soft.',
      'Add beef back, pour in stock, tomato paste and Worcestershire sauce.',
      'Add thyme, bring to simmer, cover and cook 1 hour.',
      'Add chopped vegetables, cook another 45 minutes until tender.',
      'Season and serve with crusty bread.',
    ],
  },
  {
    id: 'r010',
    name: 'Fried Rice',
    description: 'Quick weeknight fried rice — great for using up leftover rice and veg.',
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    difficulty: 'easy',
    tags: ['rice', 'asian', 'quick', 'dinner', 'leftover'],
    ingredients: [
      { name: 'cooked rice', amount: '3', unit: 'cups' },
      { name: 'eggs', amount: '3', unit: 'large' },
      { name: 'soy sauce', amount: '3', unit: 'tbsp' },
      { name: 'frozen peas', amount: '1', unit: 'cup' },
      { name: 'carrot', amount: '2', unit: 'medium' },
      { name: 'garlic', amount: '3', unit: 'cloves' },
      { name: 'sesame oil', amount: '1', unit: 'tbsp' },
      { name: 'vegetable oil', amount: '2', unit: 'tbsp' },
      { name: 'spring onions', amount: '3', unit: 'stalks' },
    ],
    instructions: [
      'Heat oil in wok or large pan over high heat.',
      'Add diced carrot and garlic, stir-fry 2 minutes.',
      'Push to side, scramble eggs in centre.',
      'Add cold rice, breaking up any clumps.',
      'Add frozen peas, soy sauce and sesame oil.',
      'Stir-fry 3–4 minutes until heated through.',
      'Serve topped with spring onions.',
    ],
  },
  {
    id: 'r011',
    name: 'Chicken and Corn Soup',
    description: 'Comforting Chinese-Aussie chicken and corn soup for the whole family.',
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 4,
    difficulty: 'easy',
    tags: ['soup', 'chicken', 'family', 'quick'],
    ingredients: [
      { name: 'chicken breast', amount: '2', unit: 'fillets' },
      { name: 'creamed corn', amount: '420', unit: 'g' },
      { name: 'chicken stock', amount: '1', unit: 'litre' },
      { name: 'eggs', amount: '2', unit: 'large' },
      { name: 'cornflour', amount: '3', unit: 'tbsp' },
      { name: 'soy sauce', amount: '1', unit: 'tbsp' },
      { name: 'spring onions', amount: '3', unit: 'stalks' },
    ],
    instructions: [
      'Poach chicken breast in stock 15 minutes. Remove and shred.',
      'Add creamed corn and soy sauce to stock, bring to simmer.',
      'Mix cornflour with 3 tbsp cold water. Stir into soup to thicken.',
      'Beat eggs and drizzle slowly into simmering soup while stirring.',
      'Return shredded chicken to soup.',
      'Serve topped with sliced spring onions.',
    ],
  },
  {
    id: 'r012',
    name: 'Pavlova',
    description: 'The great Aussie dessert — crispy meringue with soft centre and cream.',
    prep_time_minutes: 30,
    cook_time_minutes: 90,
    servings: 10,
    difficulty: 'medium',
    tags: ['dessert', 'baking', 'classic', 'pavlova', 'party'],
    ingredients: [
      { name: 'egg whites', amount: '6', unit: 'large' },
      { name: 'caster sugar', amount: '300', unit: 'g' },
      { name: 'cornflour', amount: '2', unit: 'tsp' },
      { name: 'white vinegar', amount: '1', unit: 'tsp' },
      { name: 'thickened cream', amount: '600', unit: 'ml' },
      { name: 'strawberries', amount: '250', unit: 'g' },
      { name: 'kiwi fruit', amount: '3', unit: 'whole' },
      { name: 'passionfruit', amount: '4', unit: 'whole' },
    ],
    instructions: [
      'Preheat oven to 120°C. Draw a 22cm circle on baking paper.',
      'Beat egg whites to stiff peaks.',
      'Gradually add sugar, beating until thick and glossy.',
      'Fold in cornflour and vinegar.',
      'Spread meringue within circle, making edges higher than centre.',
      'Bake 1.5 hours, then turn oven off and cool inside with door ajar.',
      'Top with whipped cream and fresh fruit before serving.',
    ],
  },
  {
    id: 'r013',
    name: 'Snag Sanga (Sausage Sandwich)',
    description: 'The iconic Bunnings snag — a sausage in bread with onion and sauce.',
    prep_time_minutes: 5,
    cook_time_minutes: 15,
    servings: 4,
    difficulty: 'easy',
    tags: ['bbq', 'sausage', 'quick', 'aussie', 'lunch'],
    ingredients: [
      { name: 'thick sausages', amount: '4', unit: 'pieces' },
      { name: 'white bread', amount: '4', unit: 'slices' },
      { name: 'onion', amount: '2', unit: 'large' },
      { name: 'tomato sauce', amount: '4', unit: 'tbsp' },
      { name: 'mustard', amount: '2', unit: 'tbsp', optional: true },
      { name: 'butter', amount: '20', unit: 'g' },
    ],
    instructions: [
      'Grill or BBQ sausages over medium heat, turning often, 12–15 minutes.',
      'Slice onions and cook in butter until caramelised.',
      'Place sausage diagonally on bread.',
      'Top with onion, tomato sauce and mustard.',
      'Fold bread. Eat immediately.',
    ],
  },
  {
    id: 'r014',
    name: 'Shepherd\'s Pie',
    description: 'Classic shepherd\'s pie with lamb mince and creamy mashed potato topping.',
    prep_time_minutes: 20,
    cook_time_minutes: 50,
    servings: 6,
    difficulty: 'medium',
    tags: ['lamb', 'dinner', 'family', 'classic', 'oven'],
    ingredients: [
      { name: 'lamb mince', amount: '600', unit: 'g' },
      { name: 'potatoes', amount: '800', unit: 'g' },
      { name: 'onion', amount: '1', unit: 'large' },
      { name: 'carrot', amount: '2', unit: 'medium' },
      { name: 'frozen peas', amount: '1', unit: 'cup' },
      { name: 'beef stock', amount: '250', unit: 'ml' },
      { name: 'tomato paste', amount: '2', unit: 'tbsp' },
      { name: 'Worcestershire sauce', amount: '1', unit: 'tbsp' },
      { name: 'milk', amount: '0.5', unit: 'cup' },
      { name: 'butter', amount: '50', unit: 'g' },
      { name: 'cheddar cheese', amount: '0.5', unit: 'cup', optional: true },
    ],
    instructions: [
      'Boil and mash potatoes with butter and milk. Season well.',
      'Brown lamb mince, drain excess fat.',
      'Add onion and carrot, cook 5 minutes.',
      'Stir in tomato paste, Worcestershire sauce and stock. Simmer 15 minutes.',
      'Add peas. Transfer to baking dish.',
      'Spread mash over top, sprinkle with cheese.',
      'Bake at 180°C for 25 minutes until golden.',
    ],
  },
  {
    id: 'r015',
    name: 'Chicken Parmigiana',
    description: 'The beloved Aussie pub classic — crumbed chicken with napoli sauce and cheese.',
    prep_time_minutes: 20,
    cook_time_minutes: 20,
    servings: 4,
    difficulty: 'medium',
    tags: ['chicken', 'dinner', 'classic', 'pub', 'family'],
    ingredients: [
      { name: 'chicken breast', amount: '4', unit: 'pieces' },
      { name: 'breadcrumbs', amount: '2', unit: 'cups' },
      { name: 'flour', amount: '0.5', unit: 'cup' },
      { name: 'eggs', amount: '2', unit: 'large' },
      { name: 'tomato passata', amount: '400', unit: 'g' },
      { name: 'mozzarella', amount: '200', unit: 'g' },
      { name: 'parmesan', amount: '50', unit: 'g' },
      { name: 'ham', amount: '4', unit: 'slices', optional: true },
      { name: 'vegetable oil', amount: '0.5', unit: 'cup' },
    ],
    instructions: [
      'Flatten chicken, coat in flour, egg and breadcrumbs.',
      'Pan-fry until golden on both sides.',
      'Place on lined baking tray.',
      'Top each schnitzel with passata, ham (optional) and cheese.',
      'Bake at 180°C for 10–12 minutes until cheese is melted.',
      'Serve with chips and salad.',
    ],
  },
  {
    id: 'r016',
    name: 'Tuna Mornay',
    description: 'Budget-friendly tuna mornay bake, a true Aussie weeknight staple.',
    prep_time_minutes: 10,
    cook_time_minutes: 30,
    servings: 4,
    difficulty: 'easy',
    tags: ['tuna', 'dinner', 'budget', 'bake', 'family'],
    ingredients: [
      { name: 'canned tuna', amount: '425', unit: 'g' },
      { name: 'macaroni pasta', amount: '2', unit: 'cups' },
      { name: 'butter', amount: '60', unit: 'g' },
      { name: 'plain flour', amount: '4', unit: 'tbsp' },
      { name: 'milk', amount: '2', unit: 'cups' },
      { name: 'cheddar cheese', amount: '1.5', unit: 'cups' },
      { name: 'peas', amount: '1', unit: 'cup' },
      { name: 'breadcrumbs', amount: '0.5', unit: 'cup' },
    ],
    instructions: [
      'Cook pasta until al dente. Drain.',
      'Make white sauce: melt butter, stir in flour, gradually whisk in milk.',
      'Cook sauce until thickened. Stir in most of cheese.',
      'Add drained tuna, peas and pasta. Mix well.',
      'Pour into baking dish, top with remaining cheese and breadcrumbs.',
      'Bake at 180°C for 20 minutes until golden.',
    ],
  },
  {
    id: 'r017',
    name: 'Banana Bread',
    description: 'Moist banana bread — perfect for overripe bananas.',
    prep_time_minutes: 15,
    cook_time_minutes: 60,
    servings: 10,
    difficulty: 'easy',
    tags: ['baking', 'snack', 'breakfast', 'banana', 'kids'],
    ingredients: [
      { name: 'ripe bananas', amount: '3', unit: 'large' },
      { name: 'plain flour', amount: '1.5', unit: 'cups' },
      { name: 'sugar', amount: '0.75', unit: 'cup' },
      { name: 'butter', amount: '100', unit: 'g' },
      { name: 'eggs', amount: '2', unit: 'large' },
      { name: 'bicarbonate of soda', amount: '1', unit: 'tsp' },
      { name: 'vanilla extract', amount: '1', unit: 'tsp' },
    ],
    instructions: [
      'Preheat oven to 180°C. Grease a loaf tin.',
      'Mash bananas well.',
      'Cream butter and sugar. Beat in eggs and vanilla.',
      'Stir in mashed banana.',
      'Fold in flour and bicarb.',
      'Pour into loaf tin. Bake 55–60 minutes.',
      'Cool in tin 10 minutes before turning out.',
    ],
  },
  {
    id: 'r018',
    name: 'Chicken Caesar Salad',
    description: 'A crowd-pleasing Caesar salad with grilled chicken and crunchy croutons.',
    prep_time_minutes: 15,
    cook_time_minutes: 15,
    servings: 4,
    difficulty: 'easy',
    tags: ['salad', 'chicken', 'lunch', 'dinner'],
    ingredients: [
      { name: 'chicken breast', amount: '2', unit: 'fillets' },
      { name: 'cos lettuce', amount: '1', unit: 'large' },
      { name: 'parmesan', amount: '80', unit: 'g' },
      { name: 'bacon', amount: '4', unit: 'rashers' },
      { name: 'eggs', amount: '2', unit: 'large' },
      { name: 'bread', amount: '2', unit: 'thick slices' },
      { name: 'caesar dressing', amount: '4', unit: 'tbsp' },
      { name: 'olive oil', amount: '2', unit: 'tbsp' },
    ],
    instructions: [
      'Cube bread, toss in oil and bake at 200°C until golden croutons.',
      'Grill chicken until cooked, slice diagonally.',
      'Crisp up bacon in pan. Soft-boil eggs 6 minutes.',
      'Tear lettuce into bowl. Add dressing and toss.',
      'Top with chicken, bacon, croutons, halved eggs and parmesan.',
    ],
  },
  {
    id: 'r019',
    name: 'Potato and Leek Soup',
    description: 'Velvety potato and leek soup — a warming winter favourite.',
    prep_time_minutes: 15,
    cook_time_minutes: 35,
    servings: 6,
    difficulty: 'easy',
    tags: ['soup', 'vegetarian', 'winter', 'potato'],
    ingredients: [
      { name: 'potatoes', amount: '6', unit: 'medium' },
      { name: 'leeks', amount: '3', unit: 'large' },
      { name: 'butter', amount: '60', unit: 'g' },
      { name: 'vegetable stock', amount: '1', unit: 'litre' },
      { name: 'cream', amount: '125', unit: 'ml' },
      { name: 'garlic', amount: '2', unit: 'cloves' },
      { name: 'chives', amount: '0.25', unit: 'cup', optional: true },
    ],
    instructions: [
      'Slice leeks (white and pale green parts) and sauté in butter 5 minutes.',
      'Add garlic and cook 1 minute.',
      'Add peeled, diced potatoes and stock.',
      'Bring to boil, simmer 25 minutes until potatoes are soft.',
      'Blend until smooth. Stir in cream.',
      'Season and serve with chives and crusty bread.',
    ],
  },
  {
    id: 'r020',
    name: 'Sausage and Vegetable Bake',
    description: 'Easy one-pan sausage and veg bake — minimal washing up!',
    prep_time_minutes: 15,
    cook_time_minutes: 45,
    servings: 4,
    difficulty: 'easy',
    tags: ['sausage', 'dinner', 'one-pan', 'family', 'oven'],
    ingredients: [
      { name: 'beef sausages', amount: '8', unit: 'pieces' },
      { name: 'potatoes', amount: '4', unit: 'medium' },
      { name: 'capsicum', amount: '2', unit: 'medium' },
      { name: 'zucchini', amount: '2', unit: 'medium' },
      { name: 'onion', amount: '2', unit: 'large' },
      { name: 'cherry tomatoes', amount: '250', unit: 'g' },
      { name: 'olive oil', amount: '3', unit: 'tbsp' },
      { name: 'mixed herbs', amount: '1', unit: 'tbsp' },
    ],
    instructions: [
      'Preheat oven to 200°C.',
      'Cut all vegetables into chunks.',
      'Toss everything with olive oil and herbs in a large baking dish.',
      'Nestle sausages among vegetables.',
      'Roast 40–45 minutes, turning once, until sausages are cooked and vegetables are tender.',
    ],
  },
  {
    id: 'r021',
    name: 'Mango Chicken Stir-Fry',
    description: 'Tropical mango chicken stir-fry — quick and fragrant.',
    prep_time_minutes: 15,
    cook_time_minutes: 15,
    servings: 4,
    difficulty: 'easy',
    tags: ['chicken', 'stir-fry', 'asian', 'mango', 'quick'],
    ingredients: [
      { name: 'chicken thighs', amount: '600', unit: 'g' },
      { name: 'mango', amount: '1', unit: 'large' },
      { name: 'capsicum', amount: '1', unit: 'large' },
      { name: 'broccoli', amount: '1', unit: 'head' },
      { name: 'soy sauce', amount: '3', unit: 'tbsp' },
      { name: 'oyster sauce', amount: '2', unit: 'tbsp' },
      { name: 'garlic', amount: '3', unit: 'cloves' },
      { name: 'ginger', amount: '2', unit: 'cm' },
      { name: 'vegetable oil', amount: '2', unit: 'tbsp' },
      { name: 'steamed rice', amount: '3', unit: 'cups' },
    ],
    instructions: [
      'Slice chicken into strips. Mix soy and oyster sauce.',
      'Heat oil in wok, cook garlic and ginger 30 seconds.',
      'Add chicken and stir-fry until browned.',
      'Add vegetables and sauce, stir-fry 4 minutes.',
      'Fold through mango pieces just before serving.',
      'Serve over steamed rice.',
    ],
  },
  {
    id: 'r022',
    name: 'French Toast',
    description: 'Thick French toast for a lazy weekend breakfast.',
    prep_time_minutes: 10,
    cook_time_minutes: 10,
    servings: 4,
    difficulty: 'easy',
    tags: ['breakfast', 'eggs', 'kids', 'weekend'],
    ingredients: [
      { name: 'thick bread slices', amount: '8', unit: 'slices' },
      { name: 'eggs', amount: '4', unit: 'large' },
      { name: 'milk', amount: '0.5', unit: 'cup' },
      { name: 'vanilla extract', amount: '1', unit: 'tsp' },
      { name: 'cinnamon', amount: '1', unit: 'tsp' },
      { name: 'butter', amount: '30', unit: 'g' },
      { name: 'maple syrup', amount: '4', unit: 'tbsp' },
      { name: 'berries', amount: '1', unit: 'cup', optional: true },
    ],
    instructions: [
      'Whisk eggs, milk, vanilla and cinnamon together.',
      'Dip bread slices in egg mixture, coating well.',
      'Melt butter in non-stick pan over medium heat.',
      'Cook bread 2–3 minutes each side until golden.',
      'Serve with maple syrup and fresh berries.',
    ],
  },
  {
    id: 'r023',
    name: 'Beef Tacos',
    description: 'Easy weeknight beef tacos with all the toppings.',
    prep_time_minutes: 15,
    cook_time_minutes: 15,
    servings: 4,
    difficulty: 'easy',
    tags: ['beef', 'dinner', 'family', 'tacos', 'Mexican'],
    ingredients: [
      { name: 'beef mince', amount: '500', unit: 'g' },
      { name: 'taco shells', amount: '12', unit: 'pieces' },
      { name: 'taco seasoning', amount: '1', unit: 'sachet' },
      { name: 'shredded lettuce', amount: '2', unit: 'cups' },
      { name: 'tomatoes', amount: '3', unit: 'medium' },
      { name: 'cheddar cheese', amount: '1', unit: 'cup' },
      { name: 'sour cream', amount: '0.5', unit: 'cup' },
      { name: 'avocado', amount: '2', unit: 'medium' },
    ],
    instructions: [
      'Brown mince in pan, drain fat.',
      'Add taco seasoning and water as per packet. Simmer 5 minutes.',
      'Warm taco shells per packet instructions.',
      'Mash avocado with a little salt and lime juice.',
      'Fill shells with mince, top with lettuce, tomato, cheese, sour cream and avocado.',
    ],
  },
  {
    id: 'r024',
    name: 'Butter Chicken',
    description: 'Rich, creamy butter chicken — a firm family favourite.',
    prep_time_minutes: 20,
    cook_time_minutes: 30,
    servings: 4,
    difficulty: 'medium',
    tags: ['chicken', 'Indian', 'curry', 'dinner', 'family'],
    ingredients: [
      { name: 'chicken thighs', amount: '700', unit: 'g' },
      { name: 'butter', amount: '60', unit: 'g' },
      { name: 'onion', amount: '1', unit: 'large' },
      { name: 'garlic', amount: '4', unit: 'cloves' },
      { name: 'ginger', amount: '3', unit: 'cm' },
      { name: 'crushed tomatoes', amount: '400', unit: 'g' },
      { name: 'cream', amount: '250', unit: 'ml' },
      { name: 'butter chicken paste', amount: '3', unit: 'tbsp' },
      { name: 'basmati rice', amount: '2', unit: 'cups' },
      { name: 'coriander', amount: '0.25', unit: 'cup', optional: true },
    ],
    instructions: [
      'Cut chicken into bite-sized pieces.',
      'Cook onion in butter until soft.',
      'Add garlic, ginger and curry paste. Stir 2 minutes.',
      'Add chicken and brown.',
      'Add crushed tomatoes, simmer 15 minutes.',
      'Stir in cream, simmer 5 minutes more.',
      'Serve over basmati rice with coriander.',
    ],
  },
  {
    id: 'r025',
    name: 'Pumpkin and Feta Salad',
    description: 'Roasted pumpkin salad with feta, spinach and pepitas.',
    prep_time_minutes: 15,
    cook_time_minutes: 25,
    servings: 4,
    difficulty: 'easy',
    tags: ['salad', 'vegetarian', 'lunch', 'pumpkin', 'summer'],
    ingredients: [
      { name: 'butternut pumpkin', amount: '600', unit: 'g' },
      { name: 'baby spinach', amount: '150', unit: 'g' },
      { name: 'feta cheese', amount: '150', unit: 'g' },
      { name: 'pepitas', amount: '0.5', unit: 'cup' },
      { name: 'red onion', amount: '0.5', unit: 'medium' },
      { name: 'olive oil', amount: '3', unit: 'tbsp' },
      { name: 'balsamic vinegar', amount: '2', unit: 'tbsp' },
      { name: 'honey', amount: '1', unit: 'tsp' },
    ],
    instructions: [
      'Cube pumpkin, toss with olive oil and salt.',
      'Roast at 200°C for 25 minutes until caramelised.',
      'Mix balsamic and honey for dressing.',
      'Arrange spinach on platter.',
      'Top with cooled pumpkin, crumbled feta, sliced red onion and pepitas.',
      'Drizzle with dressing.',
    ],
  },
  {
    id: 'r026',
    name: 'Choc Chip Cookies',
    description: 'Thick and chewy chocolate chip cookies — always a winner.',
    prep_time_minutes: 15,
    cook_time_minutes: 12,
    servings: 24,
    difficulty: 'easy',
    tags: ['baking', 'dessert', 'kids', 'snack', 'chocolate'],
    ingredients: [
      { name: 'plain flour', amount: '2.25', unit: 'cups' },
      { name: 'butter', amount: '250', unit: 'g' },
      { name: 'brown sugar', amount: '1', unit: 'cup' },
      { name: 'caster sugar', amount: '0.5', unit: 'cup' },
      { name: 'eggs', amount: '2', unit: 'large' },
      { name: 'vanilla extract', amount: '2', unit: 'tsp' },
      { name: 'bicarbonate of soda', amount: '1', unit: 'tsp' },
      { name: 'chocolate chips', amount: '2', unit: 'cups' },
    ],
    instructions: [
      'Preheat oven to 180°C.',
      'Cream butter and sugars until pale and fluffy.',
      'Beat in eggs and vanilla.',
      'Stir in flour and bicarb. Fold in chocolate chips.',
      'Roll tablespoons into balls, place on lined tray.',
      'Bake 11–12 minutes until edges are set but centre looks underdone.',
      'Cool on tray — they firm up as they cool.',
    ],
  },
  {
    id: 'r027',
    name: 'Zucchini Fritters',
    description: 'Crispy zucchini fritters — great as a side or light lunch.',
    prep_time_minutes: 15,
    cook_time_minutes: 20,
    servings: 4,
    difficulty: 'easy',
    tags: ['vegetarian', 'zucchini', 'lunch', 'side', 'quick'],
    ingredients: [
      { name: 'zucchini', amount: '4', unit: 'medium' },
      { name: 'eggs', amount: '2', unit: 'large' },
      { name: 'plain flour', amount: '0.5', unit: 'cup' },
      { name: 'parmesan', amount: '50', unit: 'g' },
      { name: 'mint', amount: '2', unit: 'tbsp' },
      { name: 'olive oil', amount: '3', unit: 'tbsp' },
      { name: 'sour cream', amount: '0.5', unit: 'cup', optional: true },
    ],
    instructions: [
      'Grate zucchini, squeeze out excess water using a tea towel.',
      'Mix zucchini with eggs, flour, parmesan and mint.',
      'Season well.',
      'Heat oil in pan. Drop spoonfuls and flatten.',
      'Cook 3 minutes per side until golden.',
      'Serve with sour cream.',
    ],
  },
  {
    id: 'r028',
    name: 'BBQ Prawn Skewers',
    description: 'Classic Aussie BBQ garlic prawn skewers.',
    prep_time_minutes: 20,
    cook_time_minutes: 10,
    servings: 4,
    difficulty: 'easy',
    tags: ['prawns', 'bbq', 'seafood', 'summer', 'gluten-free'],
    ingredients: [
      { name: 'tiger prawns', amount: '1', unit: 'kg' },
      { name: 'garlic', amount: '4', unit: 'cloves' },
      { name: 'butter', amount: '80', unit: 'g' },
      { name: 'lemon', amount: '2', unit: 'whole' },
      { name: 'parsley', amount: '0.25', unit: 'cup' },
      { name: 'olive oil', amount: '2', unit: 'tbsp' },
      { name: 'chilli flakes', amount: '0.5', unit: 'tsp', optional: true },
    ],
    instructions: [
      'Peel and devein prawns, leaving tails on. Soak wooden skewers.',
      'Thread prawns onto skewers.',
      'Mix melted butter, crushed garlic, lemon zest and parsley.',
      'Brush prawns with garlic butter.',
      'Grill on high heat 2–3 minutes per side.',
      'Serve with lemon wedges and remaining garlic butter.',
    ],
  },
  {
    id: 'r029',
    name: 'Muesli Bars',
    description: 'Chewy homemade muesli bars — perfect lunchbox snack.',
    prep_time_minutes: 15,
    cook_time_minutes: 25,
    servings: 16,
    difficulty: 'easy',
    tags: ['snack', 'lunchbox', 'kids', 'baking', 'oats'],
    ingredients: [
      { name: 'rolled oats', amount: '2', unit: 'cups' },
      { name: 'desiccated coconut', amount: '0.5', unit: 'cup' },
      { name: 'mixed seeds', amount: '0.5', unit: 'cup' },
      { name: 'dried cranberries', amount: '0.5', unit: 'cup' },
      { name: 'honey', amount: '0.5', unit: 'cup' },
      { name: 'butter', amount: '80', unit: 'g' },
      { name: 'brown sugar', amount: '0.25', unit: 'cup' },
    ],
    instructions: [
      'Preheat oven to 160°C. Line a 20×30cm baking tin.',
      'Mix oats, coconut, seeds and cranberries.',
      'Melt butter, honey and sugar together.',
      'Combine wet and dry mixtures.',
      'Press firmly into tin.',
      'Bake 20–25 minutes until golden.',
      'Score into bars while warm, cool completely before breaking apart.',
    ],
  },
  {
    id: 'r030',
    name: 'Vegetable Curry',
    description: 'Hearty vegetable curry with chickpeas — easy vegetarian dinner.',
    prep_time_minutes: 15,
    cook_time_minutes: 30,
    servings: 4,
    difficulty: 'easy',
    tags: ['vegetarian', 'vegan', 'curry', 'dinner', 'Indian'],
    ingredients: [
      { name: 'canned chickpeas', amount: '400', unit: 'g' },
      { name: 'potatoes', amount: '3', unit: 'medium' },
      { name: 'spinach', amount: '100', unit: 'g' },
      { name: 'crushed tomatoes', amount: '400', unit: 'g' },
      { name: 'coconut milk', amount: '400', unit: 'ml' },
      { name: 'curry paste', amount: '3', unit: 'tbsp' },
      { name: 'onion', amount: '1', unit: 'large' },
      { name: 'garlic', amount: '3', unit: 'cloves' },
      { name: 'basmati rice', amount: '2', unit: 'cups' },
    ],
    instructions: [
      'Sauté onion and garlic. Add curry paste, stir 2 minutes.',
      'Add diced potato and stir to coat.',
      'Add crushed tomatoes and coconut milk. Simmer 20 minutes.',
      'Add chickpeas, cook 5 more minutes.',
      'Stir through spinach until wilted.',
      'Serve with steamed basmati rice.',
    ],
  },
  {
    id: 'r031',
    name: 'Grilled Flathead with Chips',
    description: 'Classic Aussie fish and chips with flathead fillets.',
    prep_time_minutes: 15,
    cook_time_minutes: 30,
    servings: 4,
    difficulty: 'medium',
    tags: ['fish', 'chips', 'dinner', 'classic', 'aussie'],
    ingredients: [
      { name: 'flathead fillets', amount: '800', unit: 'g' },
      { name: 'potatoes', amount: '800', unit: 'g' },
      { name: 'plain flour', amount: '0.5', unit: 'cup' },
      { name: 'egg', amount: '1', unit: 'large' },
      { name: 'breadcrumbs', amount: '1', unit: 'cup' },
      { name: 'vegetable oil', amount: '1', unit: 'cup' },
      { name: 'lemon', amount: '2', unit: 'whole' },
      { name: 'tartare sauce', amount: '4', unit: 'tbsp' },
    ],
    instructions: [
      'Cut potatoes into thick chips, par-boil 5 minutes.',
      'Drain chips and oven-roast at 220°C with oil until golden.',
      'Crumb fish: flour, egg, breadcrumbs.',
      'Pan-fry fish 3–4 minutes per side.',
      'Serve with chips, lemon and tartare sauce.',
    ],
  },
  {
    id: 'r032',
    name: 'Slow Cooker Pulled Pork',
    description: 'Tender slow-cooked pulled pork for sandwiches or rice bowls.',
    prep_time_minutes: 15,
    cook_time_minutes: 480,
    servings: 8,
    difficulty: 'easy',
    tags: ['pork', 'slow-cook', 'dinner', 'batch-cook'],
    ingredients: [
      { name: 'pork shoulder', amount: '1.5', unit: 'kg' },
      { name: 'BBQ sauce', amount: '1', unit: 'cup' },
      { name: 'apple cider vinegar', amount: '0.25', unit: 'cup' },
      { name: 'brown sugar', amount: '3', unit: 'tbsp' },
      { name: 'garlic', amount: '4', unit: 'cloves' },
      { name: 'smoked paprika', amount: '2', unit: 'tsp' },
      { name: 'burger buns', amount: '8', unit: 'buns', optional: true },
    ],
    instructions: [
      'Rub pork with smoked paprika and garlic.',
      'Mix BBQ sauce, vinegar and sugar.',
      'Place pork in slow cooker, pour sauce over.',
      'Cook on low 8 hours or high 5 hours.',
      'Shred pork with two forks.',
      'Serve on buns or with rice and coleslaw.',
    ],
  },
  {
    id: 'r033',
    name: 'Tim Tam Chocolate Slice',
    description: 'No-bake Tim Tam slice — an Aussie classic for afternoon tea.',
    prep_time_minutes: 20,
    cook_time_minutes: 0,
    servings: 20,
    difficulty: 'easy',
    tags: ['dessert', 'no-bake', 'chocolate', 'slice', 'tim tam'],
    ingredients: [
      { name: 'Tim Tam biscuits', amount: '2', unit: 'packets' },
      { name: 'cream cheese', amount: '250', unit: 'g' },
      { name: 'condensed milk', amount: '395', unit: 'g' },
      { name: 'dark chocolate', amount: '200', unit: 'g' },
      { name: 'cream', amount: '100', unit: 'ml' },
    ],
    instructions: [
      'Crush Tim Tams finely in a food processor.',
      'Beat cream cheese until smooth, mix in condensed milk.',
      'Fold through crushed biscuits.',
      'Press into lined 20×30cm tin. Refrigerate 1 hour.',
      'Melt chocolate with cream. Pour over base.',
      'Refrigerate until set. Cut into squares.',
    ],
  },
  {
    id: 'r034',
    name: 'Steak with Mushroom Sauce',
    description: 'Restaurant-quality steak with a rich creamy mushroom sauce.',
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 2,
    difficulty: 'medium',
    tags: ['beef', 'steak', 'dinner', 'mushroom', 'special'],
    ingredients: [
      { name: 'sirloin steaks', amount: '2', unit: 'pieces' },
      { name: 'mushrooms', amount: '300', unit: 'g' },
      { name: 'cream', amount: '200', unit: 'ml' },
      { name: 'butter', amount: '40', unit: 'g' },
      { name: 'garlic', amount: '2', unit: 'cloves' },
      { name: 'beef stock', amount: '125', unit: 'ml' },
      { name: 'Worcestershire sauce', amount: '1', unit: 'tbsp' },
      { name: 'thyme', amount: '2', unit: 'sprigs', optional: true },
    ],
    instructions: [
      'Let steaks reach room temperature. Season generously.',
      'Sear steaks in hot cast iron pan to desired doneness. Rest.',
      'In same pan, sauté sliced mushrooms and garlic in butter.',
      'Add stock and Worcestershire sauce. Reduce by half.',
      'Add cream and simmer until thickened.',
      'Pour sauce over rested steaks. Serve with chips.',
    ],
  },
  {
    id: 'r035',
    name: 'Veggie Frittata',
    description: 'Easy oven-baked frittata packed with seasonal vegetables.',
    prep_time_minutes: 15,
    cook_time_minutes: 25,
    servings: 6,
    difficulty: 'easy',
    tags: ['eggs', 'vegetarian', 'brunch', 'lunch', 'gluten-free'],
    ingredients: [
      { name: 'eggs', amount: '8', unit: 'large' },
      { name: 'zucchini', amount: '2', unit: 'medium' },
      { name: 'capsicum', amount: '1', unit: 'large' },
      { name: 'spinach', amount: '100', unit: 'g' },
      { name: 'feta', amount: '100', unit: 'g' },
      { name: 'onion', amount: '1', unit: 'medium' },
      { name: 'milk', amount: '0.25', unit: 'cup' },
      { name: 'olive oil', amount: '2', unit: 'tbsp' },
    ],
    instructions: [
      'Preheat oven to 180°C.',
      'Sauté onion, capsicum and zucchini in oven-safe pan.',
      'Add spinach, stir until wilted.',
      'Whisk eggs with milk, salt and pepper.',
      'Pour egg mix over vegetables. Crumble feta on top.',
      'Bake 20–25 minutes until set and golden.',
    ],
  },
  {
    id: 'r036',
    name: 'Potato Salad',
    description: 'Classic creamy Aussie BBQ potato salad.',
    prep_time_minutes: 15,
    cook_time_minutes: 20,
    servings: 6,
    difficulty: 'easy',
    tags: ['salad', 'bbq', 'side', 'potato', 'summer'],
    ingredients: [
      { name: 'baby potatoes', amount: '1', unit: 'kg' },
      { name: 'bacon', amount: '4', unit: 'rashers' },
      { name: 'spring onions', amount: '4', unit: 'stalks' },
      { name: 'mayonnaise', amount: '0.5', unit: 'cup' },
      { name: 'sour cream', amount: '0.25', unit: 'cup' },
      { name: 'Dijon mustard', amount: '1', unit: 'tbsp' },
      { name: 'apple cider vinegar', amount: '1', unit: 'tbsp' },
    ],
    instructions: [
      'Boil potatoes until tender, cool and halve.',
      'Crisp up bacon, crumble when cool.',
      'Mix mayo, sour cream, mustard and vinegar for dressing.',
      'Combine potatoes, most of the bacon and spring onions.',
      'Toss with dressing.',
      'Top with remaining bacon. Refrigerate until serving.',
    ],
  },
  {
    id: 'r037',
    name: 'Homemade Pizza',
    description: 'Family pizza night — make-your-own with classic toppings.',
    prep_time_minutes: 30,
    cook_time_minutes: 15,
    servings: 4,
    difficulty: 'medium',
    tags: ['pizza', 'dinner', 'family', 'kids', 'weekend'],
    ingredients: [
      { name: 'pizza dough', amount: '500', unit: 'g' },
      { name: 'pizza sauce', amount: '0.5', unit: 'cup' },
      { name: 'mozzarella', amount: '300', unit: 'g' },
      { name: 'ham', amount: '150', unit: 'g' },
      { name: 'capsicum', amount: '1', unit: 'medium' },
      { name: 'mushrooms', amount: '150', unit: 'g' },
      { name: 'olives', amount: '0.5', unit: 'cup', optional: true },
      { name: 'olive oil', amount: '1', unit: 'tbsp' },
    ],
    instructions: [
      'Preheat oven to 230°C with pizza stone or heavy tray.',
      'Divide dough into 2, roll thin.',
      'Spread pizza sauce, top with cheese and toppings.',
      'Bake 10–15 minutes until crust is golden and cheese is bubbly.',
    ],
  },
  {
    id: 'r038',
    name: 'Chicken Noodle Soup',
    description: 'Restorative chicken noodle soup — the ultimate comfort food.',
    prep_time_minutes: 15,
    cook_time_minutes: 30,
    servings: 6,
    difficulty: 'easy',
    tags: ['soup', 'chicken', 'noodles', 'family', 'winter'],
    ingredients: [
      { name: 'chicken thighs', amount: '500', unit: 'g' },
      { name: 'egg noodles', amount: '200', unit: 'g' },
      { name: 'carrots', amount: '3', unit: 'medium' },
      { name: 'celery', amount: '3', unit: 'stalks' },
      { name: 'onion', amount: '1', unit: 'large' },
      { name: 'chicken stock', amount: '1.5', unit: 'litres' },
      { name: 'garlic', amount: '2', unit: 'cloves' },
      { name: 'parsley', amount: '0.25', unit: 'cup' },
    ],
    instructions: [
      'Bring stock to boil. Add chicken thighs and simmer 20 minutes.',
      'Remove chicken, shred and set aside.',
      'Add diced carrot, celery, onion and garlic to stock.',
      'Simmer 10 minutes.',
      'Add noodles and cook per packet.',
      'Return chicken to soup. Season, add parsley.',
    ],
  },
  {
    id: 'r039',
    name: 'Sticky Date Pudding',
    description: 'Warm, indulgent sticky date pudding with butterscotch sauce.',
    prep_time_minutes: 20,
    cook_time_minutes: 35,
    servings: 8,
    difficulty: 'medium',
    tags: ['dessert', 'baking', 'winter', 'classic', 'pudding'],
    ingredients: [
      { name: 'pitted dates', amount: '200', unit: 'g' },
      { name: 'boiling water', amount: '250', unit: 'ml' },
      { name: 'bicarbonate of soda', amount: '1', unit: 'tsp' },
      { name: 'butter', amount: '100', unit: 'g' },
      { name: 'brown sugar', amount: '0.75', unit: 'cup' },
      { name: 'eggs', amount: '2', unit: 'large' },
      { name: 'self-raising flour', amount: '1.5', unit: 'cups' },
      { name: 'cream', amount: '300', unit: 'ml' },
      { name: 'golden syrup', amount: '3', unit: 'tbsp' },
    ],
    instructions: [
      'Pour boiling water over dates and bicarb. Let soak 10 minutes.',
      'Blend date mixture until smooth.',
      'Cream butter and sugar. Beat in eggs.',
      'Fold in flour and date purée.',
      'Pour into greased 20cm square tin. Bake at 180°C for 30–35 minutes.',
      'Make sauce: simmer remaining butter, cream and golden syrup.',
      'Serve warm pudding with butterscotch sauce and ice cream.',
    ],
  },
  {
    id: 'r040',
    name: 'Prawn Cocktail',
    description: 'Classic Aussie prawn cocktail starter — simple and festive.',
    prep_time_minutes: 20,
    cook_time_minutes: 0,
    servings: 4,
    difficulty: 'easy',
    tags: ['prawns', 'starter', 'christmas', 'seafood', 'summer'],
    ingredients: [
      { name: 'cooked king prawns', amount: '800', unit: 'g' },
      { name: 'iceberg lettuce', amount: '0.5', unit: 'head' },
      { name: 'mayonnaise', amount: '0.5', unit: 'cup' },
      { name: 'tomato sauce', amount: '2', unit: 'tbsp' },
      { name: 'Worcestershire sauce', amount: '1', unit: 'tsp' },
      { name: 'lemon', amount: '1', unit: 'whole' },
      { name: 'tabasco', amount: '3', unit: 'drops', optional: true },
    ],
    instructions: [
      'Mix mayo, tomato sauce, Worcestershire sauce and tabasco for Marie Rose sauce.',
      'Shred lettuce into serving glasses.',
      'Peel prawns leaving tails on.',
      'Arrange prawns over lettuce.',
      'Dollop Marie Rose sauce over prawns.',
      'Garnish with lemon wedge.',
    ],
  },
  {
    id: 'r041',
    name: 'Pork Belly Ramen',
    description: 'Rich pork belly ramen broth with noodles and soft-boiled eggs.',
    prep_time_minutes: 30,
    cook_time_minutes: 60,
    servings: 4,
    difficulty: 'hard',
    tags: ['pork', 'ramen', 'Japanese', 'dinner', 'weekend'],
    ingredients: [
      { name: 'pork belly', amount: '600', unit: 'g' },
      { name: 'ramen noodles', amount: '400', unit: 'g' },
      { name: 'eggs', amount: '4', unit: 'large' },
      { name: 'chicken stock', amount: '1.5', unit: 'litres' },
      { name: 'soy sauce', amount: '4', unit: 'tbsp' },
      { name: 'mirin', amount: '2', unit: 'tbsp' },
      { name: 'garlic', amount: '4', unit: 'cloves' },
      { name: 'ginger', amount: '4', unit: 'cm' },
      { name: 'spring onions', amount: '4', unit: 'stalks' },
      { name: 'bamboo shoots', amount: '200', unit: 'g', optional: true },
      { name: 'nori', amount: '4', unit: 'sheets', optional: true },
    ],
    instructions: [
      'Slice pork belly and marinate in soy sauce and mirin 30 min.',
      'Simmer stock with ginger and garlic 30 minutes.',
      'Pan-fry pork belly until caramelised.',
      'Soft boil eggs 6.5 minutes, peel and halve.',
      'Cook ramen noodles, divide into bowls.',
      'Ladle broth over, top with pork, egg, spring onions and bamboo shoots.',
    ],
  },
  {
    id: 'r042',
    name: 'Mince and Corn Bake',
    description: 'Cheesy mince and corn layer bake — kids love it.',
    prep_time_minutes: 15,
    cook_time_minutes: 40,
    servings: 6,
    difficulty: 'easy',
    tags: ['beef', 'dinner', 'family', 'bake', 'kids'],
    ingredients: [
      { name: 'beef mince', amount: '500', unit: 'g' },
      { name: 'canned corn', amount: '420', unit: 'g' },
      { name: 'onion', amount: '1', unit: 'large' },
      { name: 'tomato sauce', amount: '0.5', unit: 'cup' },
      { name: 'cheddar cheese', amount: '2', unit: 'cups' },
      { name: 'mashed potato', amount: '4', unit: 'cups' },
      { name: 'Worcestershire sauce', amount: '1', unit: 'tbsp' },
    ],
    instructions: [
      'Brown mince with onion. Add tomato sauce and Worcestershire sauce.',
      'Add drained corn. Mix well.',
      'Pour into baking dish.',
      'Spread mashed potato on top.',
      'Sprinkle with cheese.',
      'Bake at 180°C for 25–30 minutes until golden.',
    ],
  },
  {
    id: 'r043',
    name: 'Lemon Butter Pasta',
    description: 'Quick and zesty lemon butter pasta — 20-minute dinner.',
    prep_time_minutes: 5,
    cook_time_minutes: 15,
    servings: 4,
    difficulty: 'easy',
    tags: ['pasta', 'quick', 'vegetarian', 'dinner', 'lemon'],
    ingredients: [
      { name: 'spaghetti', amount: '400', unit: 'g' },
      { name: 'butter', amount: '100', unit: 'g' },
      { name: 'lemon', amount: '2', unit: 'whole' },
      { name: 'garlic', amount: '3', unit: 'cloves' },
      { name: 'parmesan', amount: '80', unit: 'g' },
      { name: 'parsley', amount: '0.5', unit: 'cup' },
      { name: 'black pepper', amount: '1', unit: 'tsp' },
    ],
    instructions: [
      'Cook spaghetti until al dente, reserve 1 cup pasta water.',
      'Melt butter with garlic in wide pan.',
      'Add lemon zest and juice.',
      'Toss pasta in butter sauce, adding pasta water to loosen.',
      'Remove from heat, add parmesan and parsley.',
      'Serve immediately with extra lemon and pepper.',
    ],
  },
  {
    id: 'r044',
    name: 'Quiche Lorraine',
    description: 'Classic quiche Lorraine with bacon and gruyère.',
    prep_time_minutes: 20,
    cook_time_minutes: 40,
    servings: 6,
    difficulty: 'medium',
    tags: ['eggs', 'bacon', 'lunch', 'brunch', 'oven'],
    ingredients: [
      { name: 'shortcrust pastry', amount: '1', unit: 'sheet' },
      { name: 'bacon', amount: '6', unit: 'rashers' },
      { name: 'eggs', amount: '4', unit: 'large' },
      { name: 'cream', amount: '300', unit: 'ml' },
      { name: 'gruyère cheese', amount: '150', unit: 'g' },
      { name: 'onion', amount: '1', unit: 'small' },
      { name: 'nutmeg', amount: '0.25', unit: 'tsp' },
    ],
    instructions: [
      'Preheat oven to 180°C. Line 23cm tart tin with pastry and blind bake 15 min.',
      'Sauté chopped onion and bacon.',
      'Whisk eggs, cream and nutmeg.',
      'Scatter bacon mixture and cheese over pastry case.',
      'Pour egg mixture over.',
      'Bake 30–35 minutes until set and golden.',
    ],
  },
  {
    id: 'r045',
    name: 'Roast Chicken',
    description: 'A perfectly roasted whole chicken — Sunday dinner classic.',
    prep_time_minutes: 20,
    cook_time_minutes: 90,
    servings: 4,
    difficulty: 'easy',
    tags: ['chicken', 'roast', 'sunday', 'family', 'classic'],
    ingredients: [
      { name: 'whole chicken', amount: '1.8', unit: 'kg' },
      { name: 'butter', amount: '80', unit: 'g' },
      { name: 'lemon', amount: '1', unit: 'whole' },
      { name: 'garlic', amount: '1', unit: 'head' },
      { name: 'thyme', amount: '6', unit: 'sprigs' },
      { name: 'olive oil', amount: '2', unit: 'tbsp' },
      { name: 'salt', amount: '2', unit: 'tsp' },
      { name: 'black pepper', amount: '1', unit: 'tsp' },
    ],
    instructions: [
      'Preheat oven to 200°C.',
      'Pat chicken dry inside and out.',
      'Mix softened butter with lemon zest, thyme and garlic.',
      'Gently loosen breast skin, spread half the butter underneath.',
      'Rub remaining butter all over the outside.',
      'Place halved lemon and garlic head inside cavity.',
      'Roast 90 minutes until juices run clear.',
      'Rest 15 minutes before carving.',
    ],
  },
  {
    id: 'r046',
    name: 'Aussie Meat Pie',
    description: 'The iconic Aussie meat pie — a must-make at home.',
    prep_time_minutes: 30,
    cook_time_minutes: 50,
    servings: 6,
    difficulty: 'hard',
    tags: ['beef', 'pie', 'classic', 'aussie', 'dinner'],
    ingredients: [
      { name: 'beef mince', amount: '500', unit: 'g' },
      { name: 'shortcrust pastry', amount: '2', unit: 'sheets' },
      { name: 'puff pastry', amount: '1', unit: 'sheet' },
      { name: 'beef stock', amount: '1', unit: 'cup' },
      { name: 'tomato paste', amount: '2', unit: 'tbsp' },
      { name: 'Worcestershire sauce', amount: '1', unit: 'tbsp' },
      { name: 'cornflour', amount: '2', unit: 'tbsp' },
      { name: 'onion', amount: '1', unit: 'medium' },
      { name: 'egg', amount: '1', unit: 'large' },
    ],
    instructions: [
      'Brown mince and onion. Add tomato paste, Worcestershire sauce and stock.',
      'Simmer 20 minutes. Thicken with cornflour mixed in water.',
      'Cool filling completely.',
      'Line pie tins with shortcrust pastry.',
      'Fill with cooled mince mixture.',
      'Top with puff pastry, crimp edges, brush with egg.',
      'Bake at 200°C for 25–30 minutes until golden.',
    ],
  },
  {
    id: 'r047',
    name: 'Honey Soy Chicken',
    description: 'Sticky honey soy chicken — great over rice or noodles.',
    prep_time_minutes: 10,
    cook_time_minutes: 25,
    servings: 4,
    difficulty: 'easy',
    tags: ['chicken', 'asian', 'dinner', 'quick', 'family'],
    ingredients: [
      { name: 'chicken thighs', amount: '700', unit: 'g' },
      { name: 'honey', amount: '3', unit: 'tbsp' },
      { name: 'soy sauce', amount: '3', unit: 'tbsp' },
      { name: 'garlic', amount: '3', unit: 'cloves' },
      { name: 'ginger', amount: '2', unit: 'cm' },
      { name: 'sesame oil', amount: '1', unit: 'tsp' },
      { name: 'steamed rice', amount: '3', unit: 'cups' },
    ],
    instructions: [
      'Mix honey, soy, garlic, ginger and sesame oil.',
      'Marinate chicken at least 30 minutes.',
      'Bake at 200°C for 25–30 minutes, basting halfway.',
      'Rest 5 minutes, then slice.',
      'Serve over steamed rice with any pan juices.',
    ],
  },
  {
    id: 'r048',
    name: 'Corn Fritters',
    description: 'Crunchy corn fritters — delicious for brunch or a light dinner.',
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    difficulty: 'easy',
    tags: ['vegetarian', 'brunch', 'corn', 'quick', 'kids'],
    ingredients: [
      { name: 'canned corn', amount: '420', unit: 'g' },
      { name: 'plain flour', amount: '0.75', unit: 'cup' },
      { name: 'eggs', amount: '2', unit: 'large' },
      { name: 'milk', amount: '0.25', unit: 'cup' },
      { name: 'cheddar cheese', amount: '0.5', unit: 'cup' },
      { name: 'spring onions', amount: '3', unit: 'stalks' },
      { name: 'vegetable oil', amount: '3', unit: 'tbsp' },
      { name: 'sweet chilli sauce', amount: '3', unit: 'tbsp', optional: true },
    ],
    instructions: [
      'Mix drained corn, flour, eggs, milk, cheese and spring onions.',
      'Season with salt and pepper.',
      'Heat oil in frypan over medium heat.',
      'Drop 2 tablespoons per fritter, press flat.',
      'Cook 3 minutes per side until golden.',
      'Serve with sweet chilli sauce or sour cream.',
    ],
  },
  {
    id: 'r049',
    name: 'Carbonara',
    description: 'Silky egg-based carbonara — no cream needed.',
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 4,
    difficulty: 'medium',
    tags: ['pasta', 'bacon', 'dinner', 'quick', 'Italian'],
    ingredients: [
      { name: 'spaghetti', amount: '400', unit: 'g' },
      { name: 'bacon', amount: '200', unit: 'g' },
      { name: 'eggs', amount: '4', unit: 'large' },
      { name: 'parmesan', amount: '100', unit: 'g' },
      { name: 'garlic', amount: '2', unit: 'cloves' },
      { name: 'black pepper', amount: '2', unit: 'tsp' },
    ],
    instructions: [
      'Cook spaghetti until al dente, reserve 1 cup pasta water.',
      'Fry bacon and garlic until crispy.',
      'Whisk eggs, parmesan and black pepper together.',
      'Remove pan from heat. Add drained pasta.',
      'Quickly pour egg mixture over, tossing vigorously.',
      'Add pasta water a little at a time to achieve creamy sauce.',
      'Serve immediately with extra parmesan.',
    ],
  },
  {
    id: 'r050',
    name: 'Fairy Bread',
    description: 'The ultimate Aussie kids\' party food — buttered bread with hundreds and thousands.',
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    servings: 12,
    difficulty: 'easy',
    tags: ['snack', 'kids', 'party', 'classic', 'aussie'],
    ingredients: [
      { name: 'white bread', amount: '12', unit: 'slices' },
      { name: 'butter', amount: '100', unit: 'g' },
      { name: 'hundreds and thousands', amount: '3', unit: 'tbsp' },
    ],
    instructions: [
      'Butter each slice of bread generously.',
      'Pour hundreds and thousands onto a plate.',
      'Press buttered side of bread into the sprinkles.',
      'Cut diagonally into triangles.',
      'Serve at once.',
    ],
  },
];
